name: test github action

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: use action
        id: vectorize
        uses: ./vectorize-codebase
        with:
          include: "**/*.md,**/*.yml"
          exclude: "**/*node_modules/**/*"

      - name: upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-artifact
          path: ./${{ github.sha }}.sqlite
          retention-days: 1
          include-hidden-files: true
          overwrite: true
          if-no-files-found: error
