name: "Vectorize Repository"
description: "Vectorize Github repository"

inputs:
  exclude-pattern:
    description: "a comma-separated list of globs to ignore"
    required: false
    default: ".git"
  include-pattern:
    description: "a comma-separated list of globs to include"
    required: false
    default: "**/*"

runs:
  using: "composite"
  steps:
    - run: bun install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: bun src/index.ts --exclude-pattern ${{ inputs.exclude-pattern }} --include-pattern ${{ inputs.include-pattern }}
      shell: bash
      working-directory: ${{ github.action_path }}

branding:
  icon: "box"
  color: "blue"
